GAMEMODE:AddGroupChat(function(ply) return ply:isCP() end)
GAMEMODE:AddGroupChat(TEAM_REBEL1, TEAM_REBEL2, TEAM_REBEL3)
GAMEMODE:AddGroupChat(TEAM_CWU1, TEAM_CWU2, TEAM_CWU3, TEAM_CWU4, TEAM_CWU5, TEAM_CWU6)